/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.17
 * Generated at: 2020-06-07 11:13:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class MultiTrans_005findex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

 String top = (String)request.getAttribute("top");
 String login = (String)request.getAttribute("login");
  /*
 if(loginId==null){
  request.setAttribute("top", "/loginForm.jsp");
  request.setAttribute("login", "no");
 }else{
  request.setAttribute("top", "/MultiTrans.html");
  request.setAttribute("login", "ok");
 }*/

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>GAMMA</title>\r\n");
      out.write("\t\t<meta charset=\"utf-8\">\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\t        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("\t\t<link href=\"https://fonts.googleapis.com/css?family=Rubik:300,400,500\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/open-iconic-bootstrap.min.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/animate.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/owl.theme.default.min.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/magnific-popup.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/aos.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/ionicons.min.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/bootstrap-datepicker.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/jquery.timepicker.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/flaticon.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/icomoon.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<nav class=\"navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light\" id=\"ftco-navbar\" data-aos=\"fade-down\" data-aos-delay=\"500\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"index.html\">CBLAB - Computational Bioinformatics LABoratory</a>\r\n");
      out.write("\t\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#ftco-nav\" aria-controls=\"ftco-nav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t<span class=\"oi oi-menu\"></span> Menu\r\n");
      out.write("        \t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("        \t\t\t<div class=\"collapse navbar-collapse\" id=\"ftco-nav\">\r\n");
      out.write("          \t\t\t\t<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("            \t\t<li class=\"nav-item active\"><a href=\"index.html\" class=\"nav-link\">Home</a></li>\r\n");
      out.write("            \t\t\t\t<li class=\"nav-item\"><a href=\"GAMMA_index.jsp\" class=\"nav-link\">GAMMA</a></li>\r\n");
      out.write("            \t\t\t\t<li class=\"nav-item\"><a href=\"MultiTrans_index.jsp\" class=\"nav-link\">MultiTrans</a></li>\r\n");
      out.write("            \t\t\t\t<li class=\"nav-item\"><a href=\"NICE_index.jsp\" class=\"nav-link\">NICE</a></li>\r\n");
      out.write("            \t\t\t\t<li class=\"nav-item\"><a href=\"eQTL_index.jsp\" class=\"nav-link\">eQTL</a></li>\r\n");
      out.write("            \t\t\t\t<li class=\"nav-item\"><a href=\"Manhattan_index.jsp\" class=\"nav-link\">Manhattan</a></li>\r\n");
      out.write("            \t\t\t\t<li class=\"nav-item\"><a href=\"Signup.html\" class=\"nav-link\">SignUp</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a href=\"loginForm.jsp\" class=\"nav-link\">SignIn</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"nav-item\"><a href=\"logoutProc.jsp\" class=\"nav-link\">SignOut</a></li>\r\n");
      out.write("          \t\t\t\t</ul>\r\n");
      out.write("        \t\t\t</div>\r\n");
      out.write("      \t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<section class=\"ftco-cover\" style=\"background-image: url(images/genes_650x400_61470411347.jpg); max-width:auto; max-height:auto;\" id=\"section-home\" data-aos=\"fade\"  data-stellar-background-ratio=\"0.5\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row align-items-center ftco-vh-75\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-7\">\r\n");
      out.write("\t\t\t\t\t\t<h1 class=\"ftco-heading mb-3\" data-aos=\"fade-up\" data-aos-delay=\"500\">MultiTrans</h1>\r\n");
      out.write("            \t\t\t\t\t<h2 class=\"h5 ftco-subheading mb-5\" data-aos=\"fade-up\"  data-aos-delay=\"600\"> <a href=\"http://genetics.cs.ucla.edu/multiTrans/\" target=\"_blank\">MultiTrans</a> is an efficient and accurate multiple testing correction approach for linear mixed models. It transforms genotype data to account for genetic relatedness and heritability under linear mixed models. (Click the bold text if you want to use the program manually.)</h2>    \r\n");
      out.write("\t          \t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("      \t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"col-md-7\">\r\n");
      out.write("\t\t\t\t<h1 data-aos=\"fade-up\" data-aos-delay=\"500\">Upload files to use MultiTrans</h1> <!--  class=\"ftco-heading mb-3\"  -->\r\n");
      out.write("        \t\t\t<h2 data-aos=\"fade-up\"  data-aos-delay=\"600\">For analysis using MultiTrans, you need to upload SNP file, phenotype file and input the number of SNPs.</h2>    <!-- class=\"h5 ftco-subheading mb-5\" -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<footer class=\"ftco-footer ftco-bg-dark ftco-section\">\r\n");
      out.write("\t\t\t\t<div class=\"ftco-section contact-section\">\r\n");
      out.write("\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row block-9\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6 pr-md-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<form action=\"MultiTransServlet\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"email\" class=\"form-control\" name=\"emailAddress\" placeholder=\"The email address to receive the results.\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("            \t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("              \t\t\t\t\t\t\t\t<table  cellspacing=\"100%\">\r\n");
      out.write("              \t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("              \t\t\t\t\t\t\t\t\t\t<th cellspacing=\"50%\"><input type=\"text\" placeholder=\" Upload SNP file\" disabled></th>\r\n");
      out.write("              \t\t\t\t\t\t\t\t\t\t<th><input type=\"file\" name=\"SNPfile\"></th>\r\n");
      out.write("              \t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("              \t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("              \t\t\t\t\t\t\t\t\t\t<th cellspacing=\"50%\"><input type=\"text\" name=\"NumSNPs\" placeholder=\" The number of SNPs\"></th>\r\n");
      out.write("              \t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("              \t\t\t\t\t\t\t\t</table>\r\n");
      out.write("            \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("              \t\t\t\t\t\t\t\t<table  cellspacing=\"100%\">\r\n");
      out.write("              \t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("              \t\t\t\t\t\t\t\t\t\t<th cellspacing=\"50%\"><input type=\"text\" placeholder=\" Upload Phenotype file\" disabled></th>\r\n");
      out.write("              \t\t\t\t\t\t\t\t\t\t<th><input type=\"file\" name=\"Phenotypefile\"></th>\r\n");
      out.write("              \t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("              \t\t\t\t\t\t\t\t</table>\r\n");
      out.write("            \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("            \t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("                \t\t\t\t\t\t\t\t<input type=\"submit\" name=\"upload\" value=\"Submit\" class=\"btn btn-primary py-3 px-5\">\r\n");
      out.write("            \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("        \t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\" style=\"background-image: url(images/word_cloud.png); width:560px; height:448px;\"> </div>\r\n");
      out.write("      \t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("      \t\t\t<div class=\"row\">\r\n");
      out.write("        \t\t\t\t<div class=\"col-md-12 text-center\">\r\n");
      out.write("          \t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("        \t\t\t\t</div>\r\n");
      out.write("      \t\t\t</div>\r\n");
      out.write("\t\t\t</footer>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tif(\"");
      out.print( login );
      out.write("\"==\"no\") alert(\"You have to log in to use that.\");\r\n");
      out.write("\r\n");
      out.write("\t</script>\t\r\n");
      out.write("\t<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("  \t<script src=\"js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("  \t<script src=\"js/popper.min.js\"></script>\r\n");
      out.write("  \t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("  \t<script src=\"js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("  \t<script src=\"js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("  \t<script src=\"js/jquery.stellar.min.js\"></script>\r\n");
      out.write("  \t<script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("  \t<script src=\"js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("  \t<script src=\"js/aos.js\"></script>\r\n");
      out.write("  \t<script src=\"js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("  \t<script src=\"js/google-map.js\"></script>\r\n");
      out.write("  \t<script src=\"js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  \t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
